[package]
name = "wf_account"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x25519-dalek = "2.0.0-pre.1"
wf_auth = { path = "../wf_auth" }
wf_crypto = { path = "../wf_crypto" }